force-app/main/default/objects/Donation_Location__c/Donation_Location__c.object-meta.xml
<CustomObject>
    <description>Place where donations are dropped off and collected.</description>
    <label>Donation Location</label>
    <nameField>
        <label>Donation Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donation Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pickup__c/Pickup__c.object-meta.xml
<CustomObject>
    <description>Add this to a location when you do item pickups</description>
    <label>Pickup</label>
    <nameField>
        <label>Pickup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pickups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pickup_Line_Item__c/Pickup_Line_Item__c.object-meta.xml
<CustomObject>
    <description>An item picked up from a donation location.</description>
    <label>Pickup Line Item</label>
    <nameField>
        <displayFormat>PLI-{0000000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pickup Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pickup_Line_Item__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Value of the items in this line item</description>
    <label>Value</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Custom Product object for donation items</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of items of this product in inventory now. This field is calculated.</description>
    <inlineHelpText>The number of items of this product in inventory now. This field is calculated.</inlineHelpText>
    <label># In Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>$ value of this item</description>
    <inlineHelpText>$ value of this item</inlineHelpText>
    <label>Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <description>The weight of this product in the selected Weight Unit of Measure (Examples: 1 pound, 64 kilograms, 12 ounces)</description>
    <inlineHelpText>The weight of this product in the selected Weight Unit of Measure (Examples: 1 pound, 64 kilograms, 12 ounces)</inlineHelpText>
    <label>Weight</label>
    <precision>8</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProcessInventory_PickupSubmitted_Test.cls
@isTest
private class ProcessInventory_PickupSubmitted_Test {

    @isTest static void test_submitPickupItems() {
        
        // --- test data setup
        
        // product
        Product__c product = new Product__c(Name='TestProduct', 
                                            Value__c=1,Weight__c=1
                                           );
        insert product;
        
        // donation location
        Donation_Location__c donationLocation = new Donation_Location__c(Name='TestDonationLocation');
        insert donationLocation;
        
        // user
        Id userId = UserInfo.getUserId();
        
        // pickup
        Pickup__c pickup = new Pickup__c(Name='TestPickup', 
                                         Donation_Location__c=donationLocation.Id,
                                         Pickup_Date__c=dateTime.now(),
                                         Gear_Coordinator__c=userId);
        insert pickup;
        
        // pickup line items
        Decimal lineItemQuantity = 5;
        List<Pickup_Line_Item__c> lineItems = new List<Pickup_Line_Item__c>();
        Pickup_Line_Item__c lineItem = null;
        
        	// line item 1
        lineItem = new Pickup_Line_Item__c(Pickup__c=pickup.Id, Product__c=product.Id, Quantity__c=lineItemQuantity);
        lineItems.add(lineItem);
        
        	// line item 2
        lineItem = new Pickup_Line_Item__c(Pickup__c=pickup.Id, Product__c=product.Id, Quantity__c=lineItemQuantity);
        lineItems.add(lineItem);
        
        	// line item 3
        lineItem = new Pickup_Line_Item__c(Pickup__c=pickup.Id, Product__c=product.Id, Quantity__c=lineItemQuantity);
        lineItems.add(lineItem);
        
        System.debug('test_submitPickupItems > inserting lineItems: ' + lineItems);
        insert lineItems;
        
        // --- test
        List<Pickup__c> pickups = new List<Pickup__c>();
        pickups.add(pickup);
        System.debug('test_submitPickupItems > pickups: ' + pickups);
        
        ProcessInventory_PickupSubmitted.submitPickupItems(pickups);
        
        List<Product__c> productList = [SELECT Quantity__c FROM Product__c WHERE Id = :product.Id];
        Decimal actualQuantity = productList.get(0).Quantity__c;
        //Decimal actualGenderNeutral = productList.get(0).Gender_Neutral__c;
        //Decimal actualGenderMale = productList.get(0).Gender_Male__c;
        //Decimal actualGenderFemale = productList.get(0).Gender_Female__c;
        
        // check quantity
        Decimal expectedQuantity = lineItemQuantity * lineItems.size();
        System.debug('test_submitPickupItems > expected quantity: ' + expectedQuantity + ', actual quantity: ' + actualQuantity);
        System.assertEquals(expectedQuantity, actualQuantity, 'product quantity was not updated correctly');
        
        /*
        // check gender quantity
        System.debug('test_submitPickupItems > expected gender Neutral: ' + lineItemQuantity + ', actual: ' + actualGenderNeutral);
        System.assertEquals(lineItemQuantity, actualGenderNeutral, 'product gender Neutral quantity was not updated correctly');
        System.debug('test_submitPickupItems > expected gender Male: ' + lineItemQuantity + ', actual: ' + actualGenderMale);
        System.assertEquals(lineItemQuantity, actualGenderMale, 'product gender Male quantity was not updated correctly');
        System.debug('test_submitPickupItems > expected gender Female: ' + lineItemQuantity + ', actual: ' + actualGenderFemale);
        System.assertEquals(lineItemQuantity, actualGenderFemale, 'product gender Female quantity was not updated correctly');
        */
        
    } // end test_submitPickupItems
    
}