force-app/main/default/objects/Gear_Order__c/Gear_Order__c.object-meta.xml
<CustomObject>
    <description>Orders for baby gear</description>
    <label>Gear Order</label>
    <nameField>
        <displayFormat>GO-{000000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gear Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gear_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gear_Order__c/fields/Partner_Organization__c.field-meta.xml
<CustomField>
    <fullName>Partner_Organization__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Gear Orders</relationshipLabel>
    <relationshipName>Gear_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gear_Order_Demographic__c/Gear_Order_Demographic__c.object-meta.xml
<CustomObject>
    <label>Gear Order Demographic</label>
    <nameField>
        <displayFormat>GOD-{0000000000}</displayFormat>
        <label>Demographic Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gear Order Demographics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gear_Order_Item__c/Gear_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Gear Order Item</label>
    <nameField>
        <displayFormat>GOI-{0000000000}</displayFormat>
        <label>Order Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gear Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gear_Order_Item__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Order line item value = Quantity Fulfilled x Product Value</description>
    <label>Value</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Custom Product object for donation items</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The number of items of this product in inventory now. This field is calculated.</description>
    <inlineHelpText>The number of items of this product in inventory now. This field is calculated.</inlineHelpText>
    <label># In Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>$ value of this item</description>
    <inlineHelpText>$ value of this item</inlineHelpText>
    <label>Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <description>The weight of this product in the selected Weight Unit of Measure (Examples: 1 pound, 64 kilograms, 12 ounces)</description>
    <inlineHelpText>The weight of this product in the selected Weight Unit of Measure (Examples: 1 pound, 64 kilograms, 12 ounces)</inlineHelpText>
    <label>Weight</label>
    <precision>8</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GearOrderTrigger_Test.cls
@isTest
private class GearOrderTrigger_Test {
    
    @isTest static void test_submitted_success() {
        
        System.debug('test_submitted_success >> start');
        
        // --- test data setup
        
        // partner organization
        Account partnerOrg = new Account(Name='Test Partner Organization');
        insert partnerOrg;
        
        // order
        Gear_Order__c order = new Gear_Order__c(Partner_Organization__c=partnerOrg.Id,
                                               Order_Created__c=dateTime.now());
        insert order;                
        
        // product
        Decimal productQuantity = 5;
        Product__c product = new Product__c(Name='TestProduct',
                                           	Quantity__c=productQuantity,
                                            Value__c=1,Weight__c=1
                                           );
        insert product;
        
        // demographic
        Gear_Order_Demographic__c demographic = new Gear_Order_Demographic__c();
        demographic.Child_Age__c = 'Unknown';
        demographic.Child_Gender__c = 'Male';
        demographic.Gear_Order__c = order.Id;
        insert demographic;        

        // order line item
        Decimal quantity = 2;
        Gear_Order_Item__c lineItem = new Gear_Order_Item__c(Gear_Order__c=order.Id, 
                                                             Gear_Order_Demographic__c = demographic.Id,
                                                             Product__c=product.Id, 
                                                             Quantity__c=quantity
                                                           );
        insert lineItem;
                
        // --- test
        
        // set status
        order.Order_Status__c = 'Submitted';
        
        Test.startTest();
        Database.SaveResult result = Database.update(order);
        Test.stopTest();
        
        // verify status was changed
        System.debug('test_submitted_success >> result: ' + result);
        System.assert(result.isSuccess());
        
    } // end test_submitted_success

    
    @isTest static void test_submitted_error() {
        
        System.debug('test_submitted_error >> start');
        
        // --- test data setup
        
        // partner organization
        Account partnerOrg = new Account(Name='Test Partner Organization');
        insert partnerOrg;
        
        // order
        Gear_Order__c order = new Gear_Order__c(Partner_Organization__c=partnerOrg.Id,
                                               Order_Created__c=dateTime.now());
        insert order;                
        
        // no order line item will cause the trigger to throw an error when order status is set to "Submitted"
        
        // --- test
        
        // set status
        order.Order_Status__c = 'Submitted';
        
        Test.startTest();
        Database.SaveResult result = null;
        try {
        	result = Database.update(order);
    	} catch (Exception e) {
            System.debug('test_submitted_error >> exception: ' + e);
        }
        Test.stopTest();
        
        // verify status was changed
        System.debug('test_submitted_error >> result: ' + result);
        if (result != null) {
        	System.assert(!result.isSuccess());
        }
        
    } // end test_submitted_error

    @isTest static void test_fulfilled_success() {
        
        System.debug('test_fulfilled_success >> start');
        
        // --- test data setup
        
        // partner organization
        Account partnerOrg = new Account(Name='Test Partner Organization');
        insert partnerOrg;
        
        // order
        Gear_Order__c order = new Gear_Order__c(Partner_Organization__c=partnerOrg.Id,
                                               Order_Created__c=dateTime.now());
        insert order;                
        
        // product
        Decimal productQuantity = 5;
        Product__c product = new Product__c(Name='TestProduct',
                                           	Quantity__c=productQuantity,
                                            Value__c=1,Weight__c=1
                                           );
        insert product;
        
        // demographic
        Gear_Order_Demographic__c demographic = new Gear_Order_Demographic__c();
        demographic.Child_Age__c = 'Unknown';
        demographic.Child_Gender__c = 'Male';
        demographic.Gear_Order__c = order.Id;
        insert demographic;   

        // order line item (Fulfilled__c is true and the trigger allows the status update)
        Decimal quantity = 2;
        Gear_Order_Item__c lineItem = new Gear_Order_Item__c(Gear_Order__c=order.Id,
                                                              Gear_Order_Demographic__c = demographic.Id,
                                                              Product__c=product.Id,
                                                              Quantity__c=quantity,
                                                              Fulfilled__c=true);                             
        insert lineItem;
        
        // --- test
        
        // set status
        order.Order_Status__c = 'Fulfilled';
        
        Test.startTest();
        Database.SaveResult result = Database.update(order);
        Test.stopTest();
        
        // verify status was changed
        System.debug('test_fulfilled_success >> result: ' + result);
        System.assert(result.isSuccess());
        
    } // end test_fulfilled_success

    
    @isTest static void test_fulfilled_error() {
        
        System.debug('test_fulfilled_error >> start');
        
        // --- test data setup
        
        // partner organization
        Account partnerOrg = new Account(Name='Test Partner Organization');
        insert partnerOrg;
        
        // order
        Gear_Order__c order = new Gear_Order__c(Partner_Organization__c=partnerOrg.Id,
                                               Order_Created__c=dateTime.now());
        insert order;                
        
        // product
        Decimal productQuantity = 5;
        Product__c product = new Product__c(Name='TestProduct',
                                           	Quantity__c=productQuantity,
                                            Value__c=1,Weight__c=1
                                           );
        insert product;
        
        // demographic
        Gear_Order_Demographic__c demographic = new Gear_Order_Demographic__c();
        demographic.Child_Age__c = 'Unknown';
        demographic.Child_Gender__c = 'Male';
        demographic.Gear_Order__c = order.Id;
        insert demographic; 

        // order line item (Fulfilled__c is false and causes the trigger to throw an error)
        Decimal quantity = 2;
        Gear_Order_Item__c lineItem = new Gear_Order_Item__c(Gear_Order__c=order.Id,
                                                              Gear_Order_Demographic__c = demographic.Id,
                                                              Product__c=product.Id,
                                                              Quantity__c=quantity);                             
        insert lineItem;
        
        // set order line item as not fulfilled
        lineItem.Fulfilled__c = false;
        update lineItem;

        
        // --- test
        
        // set status
        order.Order_Status__c = 'Fulfilled';
        
        Test.startTest();
        Database.SaveResult result = null;
        try {
    		result = Database.update(order);
    	} catch (Exception e) {
            System.debug('test_submitted_error >> exception: ' + e);
        }
        Test.stopTest();
        
        // verify status was changed
        System.debug('test_fulfilled_error >> result: ' + result);
        if (result != null) {
        	System.assert(!result.isSuccess());
        }
        
    } // end test_fulfilled_error
    
} // end GearOrderTrigger_Test